{
 "title": "Amazon RDS - Performance Insights Dashboard (Commerce)",
 "description": "Amazon RDS - Performance Insights Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "rds_id",
    "label": "RDS Instance Id",
    "query": {}
   },
   { "name": "datasource", "label": "datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  { "title": "Machine Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization [All Instances]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization [Instance]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read operations [/s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write throughput [/s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Swap usage [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network out [byte/s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network in [byte/s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Load Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Session Type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "metricName": "session_type",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.user.name')} ",
     "metricName": "user",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top Application",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.application.name')} ",
     "metricName": "application",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Host",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.host.name')} ",
     "metricName": "host",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Database",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "identifier": "$db_id" },
     "label": "${PROP('Dim.db.name')} ",
     "metricName": "name",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Top SQL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.sql_tokenized.statement')} ",
     "metricName": "sql_tokenized",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "sharajag/PerfInsights-test-v4", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "db.sql_tokenized.statement", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "limit": 10,
      "orderBy": { "name": "AVG", "type": "function" },
      "orderByDirection": "DESC",
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "sql_tokenized", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(sql_tokenized) FROM \"sharajag/PerfInsights-test-v4\" GROUP BY \"db.sql_tokenized.statement\" ORDER BY AVG() DESC LIMIT 10",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Wait event",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.wait_event.type')} - ${PROP('Dim.db.wait_event.name')} ",
     "metricName": "wait_event",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database load - SQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.sql_tokenized.statement')} ",
     "metricName": "sql_tokenized",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database load - User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.user.name')} ",
     "metricName": "user",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.name')} ",
     "metricName": "name",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Wait event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "metricName": "wait_event",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Load - Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.application.name')} ",
     "metricName": "application",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Session Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.session_type.name')} ",
     "metricName": "session_type",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Load - Host",
   "type": "timeseries",
   "description": "Performance Insight metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "dimensions": { "rds_identifier": "$rds_id" },
     "label": "${PROP('Dim.db.host.name')} ",
     "metricName": "host",
     "namespace": "grafana/rds",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}